### PR TITLE
Macos

### PR DESCRIPTION
**Pull request by jhill-cmd**
Support of volatility function below mostly in back. Front still need to be worked on.

- [x] Bash
- [x] PsList
- [x] PsTree
- [x] Check_syscall
- [x] Check_sysctl
- [x] Check_trap_table
- [x] Ifconfig
- [ ] Kauth_listeners
- [ ] Kauth_scopes
- [ ] Kevents
- [x] List_Files
- [x] Lsmod
- [x] Lsof
- [x] Malfind
- [x] Mount
- [x] Netstat
- [x] Maps
- [x] Psaux
- [x] Socket_filters
- [x] VFSevents

### CODE REVIEW

**Comment by k1nd0ne** [comment]
Hello, 
Thank you for the PR!

Are you able to share the memory dump used to test this integration if any ?
You can contact me via email : k1nd0ne@mail.com.

I'll review the PR in the upcoming days. 

Best regards. 
k1nd0ne.

**Comment by jhill-cmd** [comment]
Not completely finished, the UI part is missing

**Comment by k1nd0ne** [comment]
Hello, 
Just a quick message to say I didn't forget your PR. 
VolWeb 2.0 is still in active developpement. I will use your code for the MacOS part. 

Thanks again and happy new year.

**Comment by k1nd0ne** [comment]
Hello,
I am closing this pull request. 
I am waiting for the ARM layer to be ready for Mac MX chips before updating the project. 

Thank you again for this contribution regardless.

**Pull request closed without merging**
